added VAULT_DIRS argument to allow for more than .ssh. Making example docker-vault run command accurate to match ONVAULT parameters @johnleetran

diff --git a/ONVAULT b/ONVAULT
--- a/ONVAULT
+++ b/ONVAULT
@@ -16,6 +16,11 @@ set -e
 # allow overriding default VAULT_SSH_KEY at runtime
 : ${VAULT_SSH_KEY:=id_rsa}
 
+# allow multiple dot directories to be managed
+: ${VAULT_DIRS:=ssh}
+
+: ${VAULT_IMAGE:=dockito/vault}
+
 # parse arguments
 while [[ "$#" > 1 ]]; do case $1 in
     --disable-pwd) DISABLE_PASSWORD="$2";;
@@ -33,32 +38,29 @@ log () {
 no_proxy_old="$no_proxy"
 export no_proxy="$VAULT_HOST"
 
-if ! curl -s "${VAULT_URI}/_ping"; then
+if ! curl --connect-timeout 1 -s "${VAULT_URI}/_ping"; then
   COUNTER=0
-  echo 'Waiting 10s for dockito/vault to be ready...'
-  while ! curl -s "${VAULT_URI}/_ping" && [ $COUNTER != 10 ]; do
+  echo "Waiting 10s for ${VAULT_IMAGE} to be ready..."
+  while ! curl --connect-timeout 1 -s "${VAULT_URI}/_ping" && [ $COUNTER != 10 ]; do
     sleep 1
     COUNTER=$[$COUNTER +1]
   done
 fi
 
-if curl -s "${VAULT_URI}/_ping"; then
-  mkdir -p ~/.ssh/
-
-  # check if is required the ssh backup
-  ssh_backup_enabled="$(ls -A ~/.ssh)"
-
-  # creating backup of existing ssh directory
-  if [[ -n "$ssh_backup_enabled" ]]; then
-    tmp_ssh_vault=~/".vault-backup-ssh-$(date +%s)"
-    mkdir $tmp_ssh_vault
-    cp -r ~/.ssh/* $tmp_ssh_vault
-  fi
-
+if curl --connect-timeout 1 -s "${VAULT_URI}/_ping"; then
   log "Downloading private keys..."
-  curl -s "${VAULT_URI}/ssh.tgz" | tar -C ~/.ssh/ -zxf -
-  chown -f `whoami` ~/.ssh/* || true
-  chmod -f 600 ~/.ssh/* || true
+  tmp_vault=~/".vault-backup-$(date +%s)"
+	mkdir $tmp_vault
+  for vault_dir in $VAULT_DIRS; do
+    if [[ -e ~/.${vault_dir} ]]; then
+      mv ~/.${vault_dir} ${tmp_vault}
+    fi
+		mkdir ~/.${vault_dir}
+
+    curl -s "${VAULT_URI}/${vault_dir}.tgz" | tar -C ~/.${vault_dir}/ -zxf -
+    chown -f `whoami` ~/.${vault_dir}/* || true
+    chmod -f 600 ~/.${vault_dir}/* || true
+  done
 
   log "Using ssh key: $VAULT_SSH_KEY"
   if [[  "$VAULT_SSH_KEY" != "id_rsa" ]]; then
@@ -77,15 +79,26 @@ if curl -s "${VAULT_URI}/_ping"; then
   eval $@
 
   log "Removing private keys..."
-  rm -rf ~/.ssh/*
-
-  # copying backup to ssh directory
-  if [[ -n "$ssh_backup_enabled" ]]; then
-    cp -r $tmp_ssh_vault/* ~/.ssh
-    rm -rf $tmp_ssh_vault
-  fi
+  for vault_dir in $VAULT_DIRS; do
+    rm -rf ~/.${vault_dir}
+    if [[ -e ${tmp_vault}/.${vault_dir} ]]; then
+      mv ${tmp_vault}/.${vault_dir} ~
+    fi
+  done
+  rmdir $tmp_vault
 else
-  log "ERROR: Start the dockito/vault container before using ONVAULT!"
-  log "ex: docker run -d -p ${VAULT_HOST}:14242:3000 -v ~/.ssh:/vault/.ssh dockito/vault"
+  log "ERROR: Start the ${VAULT_IMAGE} container before using ONVAULT!"
+  document_args=""
+	if [[ "$VAULT_DIRS" != "ssh" ]]; then
+		document_args="${document_args} -e VAULT_DIRS='${VAULT_DIRS}'"
+	fi
+  if [[ "$VAULT_PORT" = "tcp://${VAULT_HOST}:14242" ]]; then
+    document_args="${document_args} -p ${VAULT_HOST}:14242:3000"
+  fi
+  for vault_dir in $VAULT_DIRS; do
+    document_args="${document_args} -v ~/.${vault_dir}:/vault/.${vault_dir}"
+  done
+
+  log "ex: docker run -d${document_args} ${VAULT_IMAGE}"
   exit 1
 fi
